name: chateko_purse_admin
description: Neerd Developers

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  provider: ^4.3.2+2
  get_it: ^5.0.1
  cloud_firestore: ^0.14.0+2
  firebase_auth: ^0.18.0+1
  firebase_storage: ^4.0.0
  http: ^0.12.1
  url_launcher: ^5.5.0
  cached_network_image: ^2.3.1
  auto_size_text: ^2.1.0
  fluttertoast: ^7.0.1
  uuid: ^2.2.2
  share: ^0.6.4+5
  image: ^2.1.14
  path_provider: ^1.6.14
  shared_preferences: ^0.5.10
  image_picker: ^0.6.7+7
  location: ^3.0.2
  connectivity: ^0.4.9+2
  intl: ^0.16.1
  flushbar: ^1.10.4
  paginate_firestore: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
